cookie:
  expiry_days: 30
  key: abc
  name: abc
credentials:
  usernames:
    rosa:
      email: rosacullell@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Rosa Cullell
      password: $2b$12$M.0mXHXD9fq4n7YlWo21eeyWyeauF4D/2njSrG2wcRWFWEZfGsDNm
    ruben:
      email: estudisapcecat@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: "Rub\xC3\xA9n L\xC3\xB3pez"
      password: $2b$12$M.0mXHXD9fq4n7YlWo21eeyWyeauF4D/2njSrG2wcRWFWEZfGsDNm
    usuario:
      email: usuario@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: usuario
      password: $2b$12$4PdBfU0B1aW5Pht89Dfxd.eVxXH.tZK05rSTpzRuycPm1t.nfQQku
pre-authorized:
  emails:
  - estudisapcecat@gmail.com
  - rosacullell@gmail.com
  - usuario@gmail.com
